# Copyright (c) Ultrone Contributors. All rights reserved.
"""Code Generator — automatically generates new modules, unit tests,
integration tests, benchmark suites, and documentation from implementation plans.
"""

from __future__ import annotations

import logging
from typing import Any, Dict, List

from comms.protocol import MessageType
from knowledge_engine.base import KnowledgeSource
from research_db.schema import ImplementationPlan
from .base_agent import ResearchAgent, ResearchAgentRole

logger = logging.getLogger("Ultrone.ResearchDivision.CodeGen")


class CodeGeneratorAgent(ResearchAgent):
    """Generates code modules, tests, and documentation from plans."""

    def __init__(self, **kwargs):
        super().__init__(
            agent_id=kwargs.pop("agent_id", "code-generator-001"),
            role=ResearchAgentRole.CODER,
            **kwargs,
        )
        self.message_handlers[MessageType.RESEARCH_IMPLEMENTATION_PLAN] = self._on_plan_created
        self._generated_modules: List[str] = []

    async def run(self, *args: Any, **kwargs: Any) -> Dict[str, Any]:
        """Generate code for implementation plans."""
        plan_ids = kwargs.get("plan_ids")
        if plan_ids:
            plans = [self.research_db.get_implementation_plan(pid) for pid in plan_ids]
            plans = [p for p in plans if p is not None]
        else:
            plans = self.research_db.list_implementation_plans()

        generated = []
        for plan in plans:
            result = self._generate_from_plan(plan)
            generated.append(result)

        self._log_action("codegen_cycle", {"plans": len(generated)}, None)
        return {"generated": len(generated), "modules": self._generated_modules}

    def _on_plan_created(self, message: Any) -> Any:
        plan_id = message.content.get("plan_id")
        plan = self.research_db.get_implementation_plan(plan_id) if plan_id else None
        if plan:
            return self._generate_from_plan(plan)
        return None

    def _generate_from_plan(self, plan: ImplementationPlan) -> Dict[str, Any]:
        """Generate code modules from an implementation plan."""
        module_name = self._sanitize_name(plan.title)
        module_path = f"research_generated/{module_name}.py"

        # Generate module code
        code = self._generate_module_code(plan)
        # Generate test code
        test_code = self._generate_test_code(plan, module_name)

        # Store generated code in knowledge
        self.knowledge.store_auto_categorized(
            content=f"Generated module '{module_name}' from plan '{plan.title}':\n{code[:200]}...",
            source=KnowledgeSource.CODE,
            tags=["generated_code", "module"],
            entities=[module_name],
            confidence_score=0.7,
            layer="procedural",
            metadata={
                "plan_id": plan.plan_id,
                "module_path": module_path,
                "code": code,
                "test_code": test_code,
            },
        )

        self._generated_modules.append(module_path)
        result = {
            "plan_id": plan.plan_id,
            "module_name": module_name,
            "module_path": module_path,
            "code_length": len(code),
            "test_length": len(test_code),
        }
        self._log_action("module_generated", {"plan_id": plan.plan_id}, result)
        return result

    @staticmethod
    def _sanitize_name(name: str) -> str:
        """Convert a plan title to a valid Python module name."""
        import re

        name = re.sub(r"[^a-zA-Z0-9_]", "_", name.lower())
        name = re.sub(r"_+", "_", name).strip("_")
        return name[:60] or "generated_module"

    @staticmethod
    def _generate_module_code(plan: ImplementationPlan) -> str:
        """Generate Python module code from plan steps."""
        lines = [
            '"""',
            f"Auto-generated module: {plan.title}",
            "",
            "Generated by ULTRONE Code Generator Agent.",
            '"""',
            "",
            "from __future__ import annotations",
            "",
            "import logging",
            "from typing import Any, Dict, List, Optional",
            "",
            'logger = logging.getLogger("Ultrone.Generated")',
            "",
            "",
            "class GeneratedModule:",
            '    """Auto-generated implementation from research plan."""',
            "",
            "    def __init__(self, config: Optional[Dict[str, Any]] = None):",
            "        self.config = config or {}",
            "        self.initialized = True",
            "",
            "    def run(self, *args: Any, **kwargs: Any) -> Dict[str, Any]:",
            '        """Execute the module."""',
            "        return {",
            '            "status": "ok",',
            '            "plan_id": ' + repr(plan.plan_id) + ",",
            '            "steps": ' + str(len(plan.steps)) + ",",
            "        }",
            "",
        ]
        return "\n".join(lines)

    @staticmethod
    def _generate_test_code(plan: ImplementationPlan, module_name: str) -> str:
        """Generate pytest test code for the module."""
        lines = [
            '"""Tests for auto-generated module."""',
            "",
            "import pytest",
            "",
            f"from research_generated.{module_name} import GeneratedModule",
            "",
            "",
            "def test_module_initialization():",
            "    module = GeneratedModule()",
            "    assert module.initialized",
            "",
            "",
            "def test_module_run():",
            "    module = GeneratedModule()",
            "    result = module.run()",
            "    assert result['status'] == 'ok'",
            "",
        ]
        return "\n".join(lines)
