// ULTRONE-owned Vite config: static build for GitHub Pages.
//
// The deployment stages this build as:
//
//     site/        ->  https://<owner>.github.io/ultrone/          (docs showcase)
//     site/globe/  ->  https://<owner>.github.io/ultrone/globe/    (this console)
//
// In other words the *contents* of dist/ are served from the /ultrone/globe/
// subpath, so the build must not assume it owns the site root.
//
// `base` is therefore relative ('./') instead of the absolute
// '/ultrone/globe/'. Every URL then resolves against the document URL, which is
// the same directory the build is mounted on. An absolute base breaks the
// Cesium runtime: vite-plugin-cesium mirrors `base` into CESIUM_BASE_URL *and*
// into the output directory, so base '/ultrone/globe/' copied
// Workers/Widgets/Assets/Cesium.js to dist/ultrone/globe/cesium/ while the
// document asked for /ultrone/globe/cesium/… — every Cesium request 404'd and
// window.Cesium was never defined, so the deployed console did not boot.
// See scripts/qa-pages-assets.mjs, which fails the deployment if a referenced
// asset is missing from the staged build again.
//
// There is no Python backend on Pages, so the ULTRONE layer falls back to the
// baked-in static snapshot (public/ultrone-demo-snapshot.json, regenerated by
// pages.yml).
//
// Build with:   npm run build:pages   (or: vite build --config vite.config.pages.js)
// Verify with:  npm run qa:pages-assets
import baseConfig from './server/standalone/vite.config.js';

export default async function pagesConfig(env) {
  const base =
    typeof baseConfig === 'function' ? await baseConfig(env) : baseConfig;
  return {
    ...base,
    base: './',
  };
}
