// ULTRONE-owned Vite config: static build for GitHub Pages.
//
// Serves the console from the /ultrone/globe/ subpath with the same
// iframe-safe headers as the ULTRONE dev config. There is no Python backend
// on Pages, so the ULTRONE layer falls back to the baked-in static snapshot
// (public/ultrone-demo-snapshot.json, regenerated by pages.yml).
//
// Build with:  npm run build:pages   (or: vite build --config vite.config.pages.js)
import baseConfig from './server/standalone/vite.config.js';

export default async function pagesConfig(env) {
  const base =
    typeof baseConfig === 'function' ? await baseConfig(env) : baseConfig;
  return {
    ...base,
    base: '/ultrone/globe/',
  };
}
