apiVersion: v1
kind: Secret
metadata:
  name: ultrone-secrets
  namespace: ultrone
type: Opaque
stringData:
  POSTGRES_PASSWORD: "CHANGE_ME_POSTGRES_PASSWORD"
  GRAFANA_PASSWORD: "CHANGE_ME_GRAFANA_PASSWORD"
  REDIS_PASSWORD: "CHANGE_ME_REDIS_PASSWORD"