# Copyright (c) Ultrone Contributors. All rights reserved.
"""Tactical Synthesizer - Grammatical Evolution via Combinatorial Graph pathfinding."""

import logging
import random
import math
from typing import Dict, List, Optional, Tuple, Set
from dataclasses import dataclass
from collections import defaultdict

logger = logging.getLogger("Ultrone.Generative.TacticalSynthesizer")


@dataclass
class TacticNode:
    """A node in the tactical graph."""
    node_id: str
    domain: str
    description: str
    risk: float
    effectiveness: float
    
    # Transition weights to other nodes
    transitions: Dict[str, float] = None
    
    def __post_init__(self):
        if self.transitions is None:
            self.transitions = {}


@dataclass
class SynthesizedTactic:
    """A novel tactic generated by graph traversal."""
    tactic_id: str
    name: str
    description: str
    action_sequence: List[Tuple[str, int]]  # (node_id, tick_offset)
    domain_sequence: List[str]  # Domains involved
    novelty_score: float
    risk_score: float
    effectiveness_score: float
    cross_domain: bool
    
    def to_dict(self) -> dict:
        return {
            "tactic_id": self.tactic_id,
            "name": self.name,
            "description": self.description,
            "actions": [a[0] for a in self.action_sequence],
            "domains": self.domain_sequence,
            "novelty": round(self.novelty_score, 3),
            "risk": round(self.risk_score, 3),
            "effectiveness": round(self.effectiveness_score, 3),
        }


class TacticalGraph:
    """
    Graph of tactical primitives for Grammatical Evolution.
    
    Nodes = tactical actions
    Edges = valid transitions between actions
    DFS/A* finds valid paths for novel COAs.
    """
    
    def __init__(self):
        self.nodes: Dict[str, TacticNode] = {}
        self.edges: Dict[str, List[str]] = defaultdict(list)
        self._build_graph()
    
    def _build_graph(self):
        """Build tactical graph with valid transitions."""
        # Air domain
        self.add_node("AIR_PATROL", "air", "Establish area patrol", 0.1, 0.5,
                      {"AIR_STRIKE": 0.8, "AIR_SEAD": 0.6, "AIR_LOITER": 0.9})
        self.add_node("AIR_STRIKE", "air", "Direct kinetic engagement", 0.8, 0.9,
                      {"AIR_PATROL": 0.3, "AIR_BVR": 0.7})
        self.add_node("AIR_BVR", "air", "Beyond visual range shot", 0.3, 0.8,
                      {"AIR_STRIKE": 0.6, "AIR_LOITER": 0.4})
        self.add_node("AIR_SEAD", "air", "Suppress enemy air defenses", 0.7, 0.85,
                      {"AIR_STRIKE": 0.9, "AIR_LOITER": 0.5})
        
        # Land domain
        self.add_node("LAND_AMBUSH", "land", "Position for ambush", 0.2, 0.7,
                      {"LAND_ASSAULT": 0.8, "LAND_SUPPRESS": 0.7})
        self.add_node("LAND_ASSAULT", "land", "Close quarters attack", 0.9, 0.95,
                      {"LAND_RETREAT": 0.6, "LAND_AMBUSH": 0.4})
        self.add_node("LAND_SUPPRESS", "land", "Suppress with indirect fire", 0.4, 0.8,
                      {"LAND_ASSAULT": 0.7, "LAND_RETREAT": 0.5})
        self.add_node("LAND_RETREAT", "land", "Withdraw under cover", 0.3, 0.4,
                      {"LAND_PATROL": 0.8})
        
        # Sea domain
        self.add_node("SEA_SUBMERGE", "sea", "Go deep to evade", 0.1, 0.7,
                      {"SEA_ASW": 0.6, "SEA_TORPEDO": 0.8})
        self.add_node("SEA_ASW", "sea", "Anti-submarine patrol", 0.5, 0.8,
                      {"SEA_SUBMERGE": 0.4})
        self.add_node("SEA_TORPEDO", "sea", "Launch torpedo salvo", 0.7, 0.85,
                      {"SEA_SUBMERGE": 0.6})
        
        # Cyber domain
        self.add_node("CYBER_RECON", "cyber", "Network reconnaissance", 0.1, 0.5,
                      {"CYBER_EXPLOIT": 0.7, "CYBER_JAM": 0.6})
        self.add_node("CYBER_EXPLOIT", "cyber", "Gain system access", 0.6, 0.85,
                      {"CYBER_DISABLE": 0.8, "CYBER_EXFIL": 0.6})
        self.add_node("CYBER_DISABLE", "cyber", "Disable industrial control", 0.5, 0.9,
                      {"CYBER_EXFIL": 0.5})
        self.add_node("CYBER_JAM", "cyber", "Jam communications", 0.4, 0.7,
                      {"CYBER_RECON": 0.3, "CYBER_EXPLOIT": 0.5})
        
        # Space domain
        self.add_node("SPACE_OBSERVE", "space", "Orbital surveillance", 0.05, 0.6,
                      {"SPACE_STRIKE": 0.8, "SPACE_JAM": 0.7})
        self.add_node("SPACE_STRIKE", "space", "Orbital kinetic strike", 0.4, 0.9,
                      {"SPACE_OBSERVE": 0.5})
        self.add_node("SPACE_JAM", "space", "Electronic attack", 0.3, 0.6,
                      {"SPACE_OBSERVE": 0.4})
        
        # Cross-domain transitions (synchronization points)
        self.add_edge("CYBER_DISABLE", "AIR_STRIKE")  # Cyber enables air strike
        self.add_edge("SPACE_OBSERVE", "AIR_PATROL")  # Space supports air ISR
        self.add_edge("SEA_TORPEDO", "LAND_AMBUSH")  # Naval gunfire support
    
    def add_node(self, node_id: str, domain: str, description: str,
                 risk: float, effectiveness: float,
                 transitions: Dict[str, float] = None):
        """Add node to graph."""
        transitions = transitions or {}
        self.nodes[node_id] = TacticNode(
            node_id=node_id, domain=domain, description=description,
            risk=risk, effectiveness=effectiveness, transitions=transitions
        )
        for target in transitions:
            self.add_edge(node_id, target)
    
    def add_edge(self, source: str, target: str):
        """Add directed edge between nodes."""
        self.edges[source].append(target)
    
    def find_paths(self, start_nodes: List[str], max_depth: int = 5,
                   target_domains: Set[str] = None) -> List[List[str]]:
        """Find valid paths using DFS."""
        paths = []
        target_domains = target_domains or {"air", "land", "sea", "cyber", "space"}
        
        def dfs(current: str, path: List[str], visited: Set[str]):
            if len(path) >= 2 and len(path) <= max_depth:
                # Check if path covers multiple domains
                domains = {self.nodes[n].domain for n in path if n in self.nodes}
                if len(domains) >= 2:
                    paths.append(path.copy())
            
            if len(path) >= max_depth:
                return
            
            neighbors = self.edges.get(current, [])
            random.shuffle(neighbors)  # Non-deterministic for novelty
            
            for neighbor in neighbors:
                if neighbor not in visited:
                    visited.add(neighbor)
                    path.append(neighbor)
                    dfs(neighbor, path, visited)
                    path.pop()
                    visited.discard(neighbor)
        
        for start in start_nodes:
            dfs(start, [start], {start})
        
        return paths


class TacticalSynthesizer:
    """
    Grammatical Evolution of Tactics via Graph Pathfinding.
    
    Uses DFS to find valid sequences of 3-5 primitives across domains.
    Synchronizes actions based on graph connectivity.
    """
    
    def __init__(self):
        self.graph = TacticalGraph()
        self.synthesized_tactics: Dict[str, SynthesizedTactic] = {}
        self._tactic_history: Set[str] = set()
    
    def synthesize(
        self,
        min_length: int = 3,
        max_length: int = 5,
        cross_domain_required: bool = True,
    ) -> List[SynthesizedTactic]:
        """
        Generate novel COAs via graph pathfinding.
        
        Returns synchronized multi-domain tactics.
        """
        # Start from high-effect nodes
        start_nodes = [
            "AIR_SEAD", "CYBER_DISABLE", "SPACE_OBSERVE",
            "LAND_AMBUSH", "SEA_TORPEDO", "CYBER_EXPLOIT"
        ]
        
        # Find paths using DFS
        paths = self.graph.find_paths(
            start_nodes,
            max_depth=max_length,
        )
        
        tactics = []
        for path in paths[:20]:  # Top 20 paths
            tactic = self._create_tactic(path)
            if tactic:
                tactics.append(tactic)
        
        return tactics
    
    def _create_tactic(self, node_path: List[str]) -> Optional[SynthesizedTactic]:
        """Create tactic from node path."""
        if len(node_path) < 2:
            return None
        
        # Check novelty
        path_key = "-".join(sorted(node_path))
        if path_key in self._tactic_history:
            return None
        self._tactic_history.add(path_key)
        
        # Calculate scores
        risks = []
        effects = []
        domains = set()
        
        for node_id in node_path:
            node = self.graph.nodes.get(node_id)
            if node:
                risks.append(node.risk)
                effects.append(node.effectiveness)
                domains.add(node.domain)
        
        avg_risk = sum(risks) / len(risks) if risks else 0.5
        avg_effect = sum(effects) / len(effects) if effects else 0.5
        
        # Novelty based on path uniqueness + cross-domain count
        novelty = 0.5 + (len(domains) * 0.15) + random.uniform(-0.1, 0.2)
        novelty = min(1.0, max(0.1, novelty))
        
        # Create synchronized action sequence
        # Actions at different tick offsets based on domain coordination
        sequence = []
        for i, node_id in enumerate(node_path):
            node = self.graph.nodes.get(node_id)
            if node:
                # Cross-domain actions need synchronization
                tick_offset = i * 2
                if node.domain != node_path[max(i-1, 0)] if i > 0 else True:
                    tick_offset += 1  # Sync delay
                sequence.append((node_id, tick_offset))
        
        tactic = SynthesizedTactic(
            tactic_id=f"TACT-{random.randint(10000, 99999)}",
            name=self._name_tactic(node_path, domains),
            description=f"Graph-derived: {' → '.join(node_path)}",
            action_sequence=sequence,
            domain_sequence=list(domains),
            novelty_score=novelty,
            risk_score=avg_risk,
            effectiveness_score=avg_effect,
            cross_domain=len(domains) > 1,
        )
        
        self.synthesized_tactics[tactic.tactic_id] = tactic
        return tactic
    
    def _name_tactic(self, path: List[str], domains: Set[str]) -> str:
        """Generate tactic name from path."""
        domain_names = {
            "air": "AERIAL", "land": "GROUND", "sea": "MARITIME",
            "cyber": "CYBER", "space": "ORBITAL"
        }
        primary = " ".join(domain_names.get(d, d.upper()) for d in sorted(domains))
        
        if len(domains) >= 3:
            return f"FULL-SPECTRUM {primary} OPERATION"
        elif len(domains) == 2:
            return f"DUAL-DOMAIN {primary} COORDINATION"
        return f"{primary} MANEUVER"
    
    def get_stats(self) -> dict:
        return {
            "graph_nodes": len(self.graph.nodes),
            "graph_edges": sum(len(e) for e in self.graph.edges.values()),
            "tactics_synthesized": len(self.synthesized_tactics),
        }