apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ultrone.fullname" . }}-config
  labels:
    {{- include "ultrone.labels" . | nindent 4 }}
data:
  {{- with .Values.api.env }}
  {{- toYaml . | nindent 2 }}
  {{- end }}
  {{- if .Values.api.gpu.enabled }}
  NVIDIA_VISIBLE_DEVICES: all
  NVIDIA_DRIVER_CAPABILITIES: compute,utility
  {{- end }}