{{- if .Values.grafana.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ultrone.grafana.name" . }}
  labels:
    {{- include "ultrone.labels" . | nindent 4 }}
    app.kubernetes.io/component: grafana
spec:
  replicas: {{ .Values.grafana.replicaCount }}
  selector:
    matchLabels:
      {{- include "ultrone.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: grafana
  template:
    metadata:
      labels:
        {{- include "ultrone.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: grafana
    spec:
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.grafana.persistence.enabled }}
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: {{ include "ultrone.grafana.name" . }}-data
        - name: datasources
          configMap:
            name: {{ include "ultrone.fullname" . }}-grafana-datasources
      {{- else }}
      volumes:
        - name: data
          emptyDir: {}
        - name: datasources
          configMap:
            name: {{ include "ultrone.fullname" . }}-grafana-datasources
      {{- end }}
      containers:
        - name: grafana
          image: {{ include "ultrone.image" (dict "root" . "local" .Values.grafana.image) }}
          imagePullPolicy: {{ .Values.grafana.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.grafana.service.targetPort }}
              protocol: TCP
          env:
            - name: GF_SECURITY_ADMIN_USER
              value: {{ .Values.grafana.admin.user | quote }}
            - name: GF_SECURITY_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ultrone-secrets
                  key: GRAFANA_PASSWORD
                  optional: true
            {{- range $key, $value := .Values.grafana.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
          volumeMounts:
            - name: data
              mountPath: /var/lib/grafana
            - name: datasources
              mountPath: /etc/grafana/provisioning/datasources
          resources:
            {{- toYaml .Values.grafana.resources | nindent 12 }}
      {{- with .Values.grafana.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}