{{- if .Values.postgres.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "ultrone.postgres.name" . }}
  labels:
    {{- include "ultrone.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgres
  {{- with .Values.postgres.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.postgres.service.type }}
  ports:
    - port: {{ .Values.postgres.service.port }}
      targetPort: {{ .Values.postgres.service.targetPort }}
      protocol: TCP
      name: postgres
  selector:
    {{- include "ultrone.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: postgres
{{- end }}