{{- if or .Values.postgres.enabled .Values.grafana.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: ultrone-secrets
  labels:
    {{- include "ultrone.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if .Values.postgres.enabled }}
  {{- if .Values.postgres.database.password }}
  POSTGRES_PASSWORD: {{ .Values.postgres.database.password | quote }}
  {{- else }}
  POSTGRES_PASSWORD: {{ randAlphaNum 24 | quote }}
  {{- end }}
  {{- end }}
  {{- if .Values.grafana.enabled }}
  {{- if .Values.grafana.admin.password }}
  GRAFANA_PASSWORD: {{ .Values.grafana.admin.password | quote }}
  {{- else }}
  GRAFANA_PASSWORD: {{ randAlphaNum 24 | quote }}
  {{- end }}
  {{- end }}
  {{- if .Values.redis.enabled }}
  {{- if .Values.redis.password }}
  REDIS_PASSWORD: {{ .Values.redis.password | quote }}
  {{- else }}
  REDIS_PASSWORD: {{ randAlphaNum 24 | quote }}
  {{- end }}
  {{- end }}
  {{- if .Values.autoupdate.enabled }}
  {{- if .Values.autoupdate.githubToken }}
  GITHUB_TOKEN: {{ .Values.autoupdate.githubToken | quote }}
  {{- else }}
  GITHUB_TOKEN: ""
  {{- end }}
  {{- end }}
{{- end }}
